---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install NGINX
  ansible.builtin.apt: 
    name: nginx
    state: present
  
- name: Enable and Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy Nginx Landing Page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx