---
- name: Create SSH directory
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'

- name: Copy SSH public key
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"