---
- name: Common Configuration for all servers
  hosts: all  
  become: yes

  roles:
    - common
    - firewall

- name: Configure Staging and Development Servers
  hosts: staging:development
  become: yes

  vars:
    page_title: Apache Server
    greeting: Hello From Apache
    message: Deployed using Ansible and Jinja2

  roles:
    - apache

- name: Configure Production Server
  hosts: production
  become: yes

  vars:
    page_title: Nginx Server
    greeting: Hello From Nginx
    message: Deployed using Ansible and Jinja2

  roles:
    - nginx

